services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      args:
        - ENV=local
      target: local
    command:
      [
        "php",
        "artisan",
        "octane:start",
        "--server=frankenphp",
        "--host=0.0.0.0",
        "--port=80",
        "--admin-port=2019",
        "--watch",
      ]
    volumes:
      - type: bind
        source: ./src
        target: /app
    environment:
      - SERVER_NAME=:80
      - CADDY_GLOBAL_OPTIONS=auto_https off
      - OCTANE_SERVER=frankenphp
      # Laravel に .env ではなく .env.local を読み込ませる
      - APP_ENV=local
    networks:
      - default
      - dev-container
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=zerossl"
      - "traefik.http.services.app.loadbalancer.server.port=80"

networks:
  web:
    external: true
  dev-container:
    external: true

