services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - ENV=${ENV:-local}
      target: ${ENV:-local}
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: bind
        source: ./infra/docker/php/php.ini/php.${ENV-local}.ini
        target: /usr/local/etc/php/php.ini
    networks:
      - default
      - dev-container
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /src
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${WEB_URL}`)"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=zerossl"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"
  node:
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - type: bind
        source: ./src
        target: /src
    tty: true
    depends_on:
      - app
    ports:
      - target: 3000
        published: ${NODE_PUBLISHED_PORT:-3000}
        protocol: tcp
        mode: host
networks:
  web:
    external: true
  dev-container:
    external: true

